name: Repo syncer
on:
  schedule:
    - cron: "*/60 * * * *"
  push:
    branches:
    - master  # We mostly rely on the above cron schedule but having this
              # push handler is handy so that we re-sync after making
              # changes to our GA workflows or scripts. Unfortunately,
              # since this workflow can actually push to master it could
              # trigger itself a second time, but that second run shouldn't
              # have any updates so it will just complete quietly.
jobs:
  sync_plz_thx:
    name: Sync and push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'        # fetch all history
        token: ${{ secrets.PAT }}
    - name: ./actions/syncer/
      uses: ./actions/syncer/
    - name: The job has failed
      if: ${{ failure() }}
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        filename: .github/sync-failed-template.md
